version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "Composer"
      include: "scope"
    groups:
      composer-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily
    labels:
      - dependencies
      - documentation
    commit-message:
      prefix: "Docs npm"
      include: "scope"
    groups:
      docs-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "Docker"
      include: "scope"
    groups:
      docker-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: "Docker Compose"
      include: "scope"
    groups:
      docker-compose-all:
        patterns:
          - "*"
