version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "Composer"
      include: "scope"
    groups:
      composer-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
