#!/usr/bin/env php
<?php

/**
 * TorrentPier – Bull-powered BitTorrent tracker engine
 *
 * Bull CLI - Command Line Interface for TorrentPier
 * Usage: php bull <command> [options] [arguments]
 *
 * @copyright Copyright (c) 2005-2025 TorrentPier (https://torrentpier.com)
 * @link      https://github.com/torrentpier/torrentpier for the canonical source repository
 * @license   https://github.com/torrentpier/torrentpier/blob/master/LICENSE MIT License
 */

if (PHP_SAPI !== 'cli') {
    die('Bull CLI must be run from the command line.');
}

const BB_ROOT = __DIR__ . '/';

// Bootstrap the application
require __DIR__ . '/library/common.php';

// Create and run the console kernel
$kernel = new App\Kernels\ConsoleKernel(app());

try {
    $exitCode = $kernel->handle();
} catch (Exception $e) {
    fwrite(STDERR, "Error: {$e->getMessage()}\n");
    $exitCode = 1;
}

// Terminate the kernel
$kernel->terminate(
    new Symfony\Component\Console\Input\ArgvInput,
    $exitCode,
);

exit($exitCode);
