name: TorrentPier nightly builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Get commit hash
        id: get_commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Create archive
        run: |
          commit=${{ steps.get_commit_hash.outputs.commit_hash }}
          zip_name="torrentpier-$commit.zip"
          zip -r "$zip_name" . -x ".git/*" ".github/*"
          echo "::set-output name=zip_name::$zip_name"
        id: create_zip

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: TorrentPier
          path: ${{ steps.create_zip.outputs.zip_name }}
