name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: v2.4.5-rc.2.. --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Commit changelog
        run: |
          git checkout master
          git config --local user.name 'belomaxorka'
          git config --local user.email 'roman25052006.kelesh@gmail.com'
          set +e
          git add CHANGELOG.md
          git commit -m "release(preparing): Update CHANGELOG.md 📖"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master

  checksums:
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.REPO_TOKEN }}

      - name: Generate checksums.md5 file
        run: |
          find . -type f -not -path "./.git/*" -exec md5sum {} \; > internal_data/checksums.md5

      - name: Commit and push checksums.md5 if changed
        run: |
          git checkout master
          git config --local user.name 'belomaxorka'
          git config --local user.email 'roman25052006.kelesh@gmail.com'

          if git diff --quiet internal_data/checksums.md5; then
            echo "No changes in internal_data/checksums.md5"
          else
            set +e
            git add internal_data/checksums.md5
            git commit -m "release(preparing): Update checksums.md5 📄"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master
          fi

  release:
    name: Create release
    needs:
      - checksums
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: torrentpier-${{ env.RELEASE_VERSION }}*
          asset_name: mything
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "TorrentPier v${{ env.RELEASE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"

      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: torrentpier-${{ env.RELEASE_VERSION }}*
          asset_name: mything
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "TorrentPier v${{ env.RELEASE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
