name: Changelog & checksums generation

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.REPO_TOKEN }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: v2.4.5-rc.2.. --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Generate checksums.md5 file
        run: |
          find . -type f -not -path "./.git/*" -exec md5sum {} \; > internal_data/checksums.md5

      - name: Commit changes (changelog & updated checksums)
        run: |
          git checkout master
          git config user.name 'belomaxorka'
          git config user.email 'roman25052006.kelesh@gmail.com'
          set +e
          if git diff --quiet internal_data/checksums.md5; then
            echo "No changes in internal_data/checksums.md5"
          else
            git add internal_data/checksums.md5
          fi
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md & checksums.md5"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master
