name: Changelog generation

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Commit changelog
        run: |
          git checkout master
          git config user.name 'belomaxorka'
          git config user.email 'roman25052006.kelesh@gmail.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md 📖"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master
