name: Generate Checksums

on:
  push:
    branches:
      - master

jobs:
  generate-checksums:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate MD5 checksums
        run: |
          find . -type f -not -path "./.git/*" -exec md5sum {} \; > internal_data/checksums.md5

      - name: Commit and push checksums.md5 if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if git diff --quiet checksums.md5; then
            echo "No changes in checksums.md5"
          else
            git add checksums.md5
            git commit -m "Update checksums.md5 📄"
            git push
          fi
