name: Build and Push Docker Image

on:
  push:
    branches:
      - v2.4
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/TorrentPier:latest .

      - name: Tag image with release version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${{ github.repository_owner }}/TorrentPier:latest ghcr.io/${{ github.repository_owner }}/TorrentPier:$VERSION

      - name: Push latest tag
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/TorrentPier:latest

      - name: Push version tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository_owner }}/TorrentPier:$VERSION
